//
//  PickLocationOnMapPresenter.swift
//  DoorDashDemo
//
//  Created by Saikumar Kankipati on 12/25/18.
//  Copyright (c) 2018 Saikumar Kankipati. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickLocationOnMapPresentationLogic {
  func present(response: Any)
}

class PickLocationOnMapPresenter: PickLocationOnMapPresentationLogic {
  weak var viewController: PickLocationOnMapDisplayLogic?
  
  // MARK: Do something
  
	func present(response: Any) {
		switch response {
		case is [GetRestaurantsListResponseModel]:
			guard let responseModel = response as? [GetRestaurantsListResponseModel] else {
				return
			}
		
			viewController?.getRestaurantsListComplete(response: responseModel)
			
		case is Error:
			viewController?.displayNetworkError()
		default:
			viewController?.displayNetworkError()
		}
	}
}
