//
//  PickLocationOnMapPresenter.swift
//  DoorDashDemo
//
//  Created by Saikumar Kankipati on 12/25/18.
//  Copyright (c) 2018 Saikumar Kankipati. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickLocationOnMapPresentationLogic {
  func presentSomething(response: PickLocationOnMap.Something.Response)
}

class PickLocationOnMapPresenter: PickLocationOnMapPresentationLogic {
  weak var viewController: PickLocationOnMapDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PickLocationOnMap.Something.Response) {
    let viewModel = PickLocationOnMap.Something.ViewModel()
  }
}
