//
//  PickLocationOnMapRouter.swift
//  DoorDashDemo
//
//  Created by Saikumar Kankipati on 12/25/18.
//  Copyright (c) 2018 Saikumar Kankipati. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickLocationOnMapRoutingLogic {
	func navigateToRestaurantsListScene(response: [GetRestaurantsListResponseModel])
}

class PickLocationOnMapRouter: NSObject, PickLocationOnMapRoutingLogic {
  weak var viewController: PickLocationOnMapViewController?
  var dataStore: PickLocationOnMapDataStore?
  
  // MARK: Routing
	
	func navigateToRestaurantsListScene(response: [GetRestaurantsListResponseModel]) {
		let destination = RestarantsListViewController.getInstance()
		destination.dataSource = response

		self.viewController?.navigationController?.pushViewController(destination, animated: true)
	}
}
